/**
 * @file    rtc_manager.h
 * @brief   RTC management service – thin wrapper around STM32 HAL RTC
 *          providing time-of-day, calendar, and watering-window helpers.
 * @author  ltc1342
 * @date    2026-07-01
 *
 * @note    The HAL RTC handle (hrtc) is generated by CubeMX and lives in
 *          Core/Src/rtc.c.  Pass its address to rtc_manager_init().
 *
 *          Forbidden watering period (midday heat protection):
 *            FORBIDDEN_START_HOUR – FORBIDDEN_END_HOUR  (app_defs.h)
 *          e.g. 10:00 – 15:00.
 *
 *          Weekday convention (HAL RTC):
 *            RTC_WEEKDAY_MONDAY    = 1
 *            RTC_WEEKDAY_TUESDAY   = 2
 *            ...
 *            RTC_WEEKDAY_SUNDAY    = 7
 *
 *          Usage:
 *          @code
 *            extern RTC_HandleTypeDef hrtc;   // CubeMX generated
 *            static RtcManager_t rtc_mgr;
 *            rtc_manager_init(&rtc_mgr, &hrtc);
 *
 *            TimeOfDay_t  now;
 *            DateOfDay_t  today;
 *            rtc_manager_get_time(&rtc_mgr, &now);
 *            rtc_manager_get_date(&rtc_mgr, &today);
 *
 *            if (rtc_manager_is_forbidden(&rtc_mgr)) { // skip watering }
 *          @endcode
 */

#ifndef RTC_MANAGER_H_
#define RTC_MANAGER_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include "app_types.h"    /* TimeOfDay_t                       */
#include "app_defs.h"     /* FORBIDDEN_START_HOUR / _END_HOUR  */

/* ============================================================================
 *   TYPES
 * ============================================================================ */

/**
 * @brief  Calendar date with weekday.
 * @note   Year is stored as offset from 2000 (e.g. 26 → 2026).
 *         weekday: 1 = Monday … 7 = Sunday (HAL convention).
 */
typedef struct {
    uint8_t year;       /**< 0 – 99 (offset from 2000) */
    uint8_t month;      /**< 1 – 12                    */
    uint8_t day;        /**< 1 – 31                    */
    uint8_t weekday;    /**< 1 = Mon … 7 = Sun         */
} DateOfDay_t;

/**
 * @brief  RTC manager instance.
 * @note   hrtc is stored as void* to avoid pulling stm32f4xx_hal_rtc.h
 *         into every translation unit that includes this header.
 *         The .c file casts it to RTC_HandleTypeDef*.
 */
typedef struct {
    void *hrtc;         /**< Pointer to RTC_HandleTypeDef (injected at init) */
    bool  initialized;
} RtcManager_t;

/* ============================================================================
 *   API
 * ============================================================================ */

/**
 * @brief  Initialise RTC manager.
 * @param  mgr   Manager instance (must not be NULL).
 * @param  hrtc  Pointer to CubeMX-generated RTC_HandleTypeDef (must not be NULL).
 * @return ERR_NONE on success, ERR_INVALID_PARAM on NULL.
 */
ErrorCode_t rtc_manager_init(RtcManager_t *mgr, void *hrtc);

/**
 * @brief  Read the current time from the RTC.
 * @param  mgr      Initialised manager.
 * @param  time_out Destination structure (must not be NULL).
 * @return ERR_NONE on success, ERR_HW_INIT_FAIL on HAL error.
 */
ErrorCode_t rtc_manager_get_time(const RtcManager_t *mgr,
                                  TimeOfDay_t        *time_out);

/**
 * @brief  Read the current calendar date from the RTC.
 * @param  mgr      Initialised manager.
 * @param  date_out Destination structure (must not be NULL).
 * @return ERR_NONE on success, ERR_HW_INIT_FAIL on HAL error.
 */
ErrorCode_t rtc_manager_get_date(const RtcManager_t *mgr,
                                  DateOfDay_t        *date_out);

/**
 * @brief  Set the RTC time (e.g. after receiving NTP sync from ESP32).
 * @param  mgr   Initialised manager.
 * @param  time  New time to write.
 * @return ERR_NONE on success.
 */
ErrorCode_t rtc_manager_set_time(RtcManager_t      *mgr,
                                  const TimeOfDay_t *time);

/**
 * @brief  Set the RTC calendar date.
 * @param  mgr   Initialised manager.
 * @param  date  New date to write.
 * @return ERR_NONE on success.
 */
ErrorCode_t rtc_manager_set_date(RtcManager_t      *mgr,
                                  const DateOfDay_t *date);

/**
 * @brief  Check whether the current time is inside the forbidden
 *         watering window (FORBIDDEN_START_HOUR – FORBIDDEN_END_HOUR).
 * @param  mgr  Initialised manager.
 * @return true  – watering must be suppressed (midday heat).
 *         false – watering is permitted.
 */
bool rtc_manager_is_forbidden(const RtcManager_t *mgr);

/**
 * @brief  Return the elapsed seconds since midnight for a given time.
 * @param  time  Time to convert.
 * @return Seconds since 00:00:00 (0 – 86399).
 */
uint32_t rtc_manager_time_to_seconds(const TimeOfDay_t *time);

/**
 * @brief  Compare two TimeOfDay_t values.
 * @return -1 if a < b, 0 if a == b, +1 if a > b.
 */
int8_t rtc_manager_compare_time(const TimeOfDay_t *a, const TimeOfDay_t *b);

#ifdef __cplusplus
}
#endif

#endif /* RTC_MANAGER_H_ */
